service:
  name: serverless-bittorrent-tracker

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  logs:
    httpApi: true

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'
